version: '3.7'
services:
  mysql:
    image: postgres:latest
    container_name: postgresql_77Days
    ports:
      - "3900:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    restart: always